// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwkkcXD2-zdxqtvxuLxddY99rP4dn7Vpg',
    appId: '1:818990584712:web:bebd8b29cd591c749ca03d',
    messagingSenderId: '818990584712',
    projectId: 'decart-a1ac7',
    authDomain: 'decart-a1ac7.firebaseapp.com',
    databaseURL: 'https://decart-a1ac7-default-rtdb.firebaseio.com',
    storageBucket: 'decart-a1ac7.firebasestorage.app',
    measurementId: 'G-HZ6X665NFE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWo9LOaDA6cHCVwQWarzJSMVZNYHycNZY',
    appId: '1:818990584712:android:37f99197a14605719ca03d',
    messagingSenderId: '818990584712',
    projectId: 'decart-a1ac7',
    databaseURL: 'https://decart-a1ac7-default-rtdb.firebaseio.com',
    storageBucket: 'decart-a1ac7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcQ9P8FvqsYWI47D_E1XYwXtzEYspSqKk',
    appId: '1:818990584712:ios:33359bee3629c0d09ca03d',
    messagingSenderId: '818990584712',
    projectId: 'decart-a1ac7',
    databaseURL: 'https://decart-a1ac7-default-rtdb.firebaseio.com',
    storageBucket: 'decart-a1ac7.firebasestorage.app',
    iosBundleId: 'com.example.decartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcQ9P8FvqsYWI47D_E1XYwXtzEYspSqKk',
    appId: '1:818990584712:ios:33359bee3629c0d09ca03d',
    messagingSenderId: '818990584712',
    projectId: 'decart-a1ac7',
    databaseURL: 'https://decart-a1ac7-default-rtdb.firebaseio.com',
    storageBucket: 'decart-a1ac7.firebasestorage.app',
    iosBundleId: 'com.example.decartApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBwkkcXD2-zdxqtvxuLxddY99rP4dn7Vpg',
    appId: '1:818990584712:web:873bbe529d6b984c9ca03d',
    messagingSenderId: '818990584712',
    projectId: 'decart-a1ac7',
    authDomain: 'decart-a1ac7.firebaseapp.com',
    databaseURL: 'https://decart-a1ac7-default-rtdb.firebaseio.com',
    storageBucket: 'decart-a1ac7.firebasestorage.app',
    measurementId: 'G-WE7MQXZ26J',
  );
}
